import Header from '../components/Header.jsx';
import Footer from '../components/Footer.jsx';
import { IconExternalLink } from '../components/icons.jsx';
import './legalDisclaimer.css';

const LEGAL_CARDS = [
  {
    icon: '🔬',
    color: 'var(--km-blue)',
    title: 'Our App & AI Usage',
    paragraphs: [
      'America Smiles is powered by conversational AI. To help us turn everyday objects into sparks for connection, our app uses software tools from OpenAI, Google, and Streamlit.',
      'We are always learning and testing as we continue to grow!',
    ],
  },
  {
    icon: '🧭',
    color: 'var(--km-teal)',
    title: 'Independent Policies',
    paragraphs: [
      'We are an independent nonprofit organization. Our mission, goals, and kindness ideas belong entirely to America Smiles and are separate from the companies that make our software tools (like OpenAI, Google, and Streamlit).',
    ],
  },
  {
    icon: '⚠️',
    color: 'var(--km-orange)',
    title: 'Accuracy & Human Oversight',
    paragraphs: [
      'America Smiles uses AI, and AI can make mistakes. While we do our best to look over everything, AI-generated ideas can occasionally be incorrect.',
      'Please always use your best judgment and prioritize real-world safety.',
    ],
  },
  {
    icon: '📘',
    color: 'var(--km-purple)',
    title: 'Nature of Information',
    paragraphs: [
      'Everything shared on this site is for general informational and everyday kindness purposes only. The ideas generated by our app do not constitute professional, legal, medical, or financial advice.',
    ],
  },
  {
    icon: '⚖️',
    color: 'var(--km-coral)',
    title: 'Limitation of Liability',
    paragraphs: [
      'By using this site, you agree to use our tools safely and responsibly. America Smiles, Westport Smiles, and our team are not liable for any issues or damages resulting from your reliance on the kindness ideas or information provided here.',
    ],
  },
  {
    icon: '💙',
    color: 'var(--km-orange)',
    title: 'Our Commitment',
    highlight: true,
    paragraphs: [
      'We are dedicated to using AI-powered kindness to bring people closer together. We appreciate your patience and feedback as we continue to test our app and build a kinder neighborhood, one smile at a time!',
    ],
  },
];

const LEARN_MORE_LINKS = [
  { href: 'https://openai.com/policies/usage-policies', label: 'OpenAI Usage Policies' },
  { href: 'https://ai.google/principles/', label: 'Google AI Principles' },
  { href: 'https://streamlit.io/terms-of-use', label: 'Streamlit Terms of Service' },
];

export default function LegalDisclaimer() {
  return (
    <div className="ld-page">
      <Header variant="home" />

      <main className="ld-main">
        <section className="ld-section">
          <div className="ld-wrap">
            <div className="ld-header">
              <span className="ld-tag">Transparency</span>
              <h1 className="ld-title">Legal Disclaimer &amp; Technology Disclosure</h1>
              <p className="ld-subtitle">
                We believe in being open about how we work, who we are, and the technology that powers our mission.
              </p>
            </div>

            <div className="ld-grid">
              {LEGAL_CARDS.map((c) => (
                <div key={c.title} className={`ld-card ${c.highlight ? 'ld-card--highlight' : ''}`} style={{ '--card-color': c.color }}>
                  <div className="ld-card-icon">{c.icon}</div>
                  <h3 className="ld-card-title">{c.title}</h3>
                  {c.paragraphs.map((p, i) => <p key={i}>{p}</p>)}
                </div>
              ))}
            </div>

            <div className="ld-links-block">
              <h3>Learn More</h3>
              <p>To learn more about the tools behind our app, you can review:</p>
              <div className="ld-pill-row">
                {LEARN_MORE_LINKS.map((l) => (
                  <a key={l.href} href={l.href} target="_blank" rel="noopener noreferrer" className="ld-pill">
                    <IconExternalLink /> {l.label}
                  </a>
                ))}
              </div>
            </div>
          </div>
        </section>
      </main>

      <div className="ld-footer-fixed">
        <Footer />
      </div>
    </div>
  );
}
